# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flight_information_varint.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66light_information_varint.proto\x12\x1f\x66light_information_proto_varint\"\x8c\x01\n\x1a\x66light_information_message\x12\x10\n\x03LAT\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x10\n\x03LON\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x10\n\x03\x41LT\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x14\n\x07heading\x18\x04 \x01(\rH\x03\x88\x01\x01\x42\x06\n\x04_LATB\x06\n\x04_LONB\x06\n\x04_ALTB\n\n\x08_headingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_information_varint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FLIGHT_INFORMATION_MESSAGE']._serialized_start=69
  _globals['_FLIGHT_INFORMATION_MESSAGE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
